### ISSUE TITLE
Style reference

### ISSUE THREAD

**Issue by Ileriayo** [emmanuelkehinde/TwittaSave-Android#1]
Hi Kenny,
Can't find 'Base.TextAppearance.AppCompat.Body2'in styles.xml. android:textAppearance="@style/Base.TextAppearance.AppCompat.Body2"(activity_about.xml)

**Comment by emmanuelkehinde** [comment]
Thanks for contacting.

Are you sure your AppCompat dependencies are alright?

Base.TextAppearance.AppCompat.Body2 seems to be default String options that aren't set by myself.
I think it all falls on supporting AppCompat.

**Comment by emmanuelkehinde** [comment]
If it doesn't work eventually, you may remove that line of code, while you work on the features you want to work on. :+1:

**Comment by Ileriayo** [comment]
Alright.
