### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mjsal** [emmanuelkehinde/TwittaSave-Android#10]
App is not working, keeps saying check your internet connection wen I hit the download button

**Comment by emmanuelkehinde** [comment]
Hi @mjsal 

Thanks for bringing this to my attention. Have you tried installing the latest version?

https://github.com/emmanuelkehinde/TwittaSave-Android/releases/download/v3.0/twittasave-release.apk

**Comment by mjsal** [comment]
yes It's working now thanks, it's a great app why don't you publish to the play store?

**Comment by emmanuelkehinde** [comment]
> yes It's working now thanks, it's a great app why don't you publish to the play store?

Thanks @mjsal 
I had it on the play store previously but by account got terminated after some time. That's why I've been sharing here on GitHub through the readme.

**Comment by mjsal** [comment]
Did it get terminated because of this app? I don’t think it’s against play store policies

**Comment by emmanuelkehinde** [comment]
Closing this issue as it's addressed.
