### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by ghost** [emmanuelkehinde/TwittaSave-Android#13]
Could you please Add dark mode and the app can download pictures?

**Comment by emmanuelkehinde** [comment]
Thanks for the feature request @venya-san. Will definitely look into it.

**Comment by emmanuelkehinde** [comment]
Hello @venya-san, dark mode support has been added with this [PR](https://github.com/emmanuelkehinde/TwittaSave-Mobile/pull/14)
Also, a [new release](https://github.com/emmanuelkehinde/TwittaSave-Mobile/releases/tag/v4.1) is available regarding that.
We won't be adding the pictures feature as it's one of the basic functionalities of the Twitter app already.

Thank you for using TwittaSave.
