### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [emmanuelkehinde/TwittaSave-Android#4]
Currently, the app can only be installed via Playstore. The app being open source, would you mind providing the `.apk` by other means, e.g. via Github `releases/` (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help)?

**Comment by emmanuelkehinde** [comment]
Thank you for pointing that out. I will do the needful ASAP.

**Comment by emmanuelkehinde** [comment]
Done!

**Comment by IzzySoft** [comment]
Thanks! It's [available via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.kehinde.twittasave) now as well. And sorry for the late answer, somehow I didn't get a notification.

**Comment by emmanuelkehinde** [comment]
Cool. Thanks

**Comment by IzzySoft** [comment]
Anytime :wink: Just please remember to create a new tag and attach the APK to it whenever releasing a new version. My updater will then automatically fetch the new APK for my repo.
