### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by saudkamran** [emmanuelkehinde/TwittaSave-Android#5]
@Override
            public void failure(TwitterException exception) {
       //         progressDialog.hide();
                Toast.makeText(Download_Auto.this, "Request Failed: Check your internet connection", Toast.LENGTH_SHORT).show();
            }
exception due to twitter key . how can i get twitter key ???

**Comment by emmanuelkehinde** [comment]
Hello, visit https://developer.twitter.com/en/apps to create a new app and thereby get a key and secret.

**Comment by saudkamran** [comment]
Developers account not approved

**Comment by emmanuelkehinde** [comment]
Twitter developer account? You should be able to create one in a few minutes.

**Comment by saudkamran** [comment]
yes developer account they need info i gave but not approved

**Comment by saudkamran** [comment]
![image](https://user-images.githubusercontent.com/30626891/56407523-7e91bd00-628a-11e9-9878-8b4c4017bbd9.png)

**Comment by emmanuelkehinde** [comment]
Oh. I can't really tell what caused that. But you can reach out to Twitter Support for help.

**Comment by saudkamran** [comment]
Please help me for approval of twitter developers account

**Comment by emmanuelkehinde** [comment]
Hey. I don't work with twitter. Reach out to their customer support.

**Comment by saudkamran** [comment]
okay  thank you

**Comment by emmanuelkehinde** [comment]
You are welcome.
