### ISSUE TITLE
Change of package name?

### ISSUE THREAD

**Issue by IzzySoft** [emmanuelkehinde/TwittaSave-Android#7]
Looks like the package name changed with the last release, from `com.kehinde.twittasave` to `com.emmanuelkehinde.twittasave`. As that means users would have to re-install direct update won't work): was that intended? And if so, will the new name stay, making the new version a successor of the "old app"?

**Comment by emmanuelkehinde** [comment]
Hi @IzzySoft, thanks for the notice. Yes, I changed the package name to allow for a new upload on playstore but unfortunately the new release wasn’t accepted, which then made me resort to placing the update here, but I didn’t change the package back to the usual one. Thanks for bring it to my notice, I will revert it and make it available soon.

**Comment by emmanuelkehinde** [comment]
UPDATE:

I won’t be reverting it. Since, a lot of people have downloaded the new release, I’ve decided to keep it that way and go with the flow.
I hope you enjoy it 🙂

**Comment by IzzySoft** [comment]
Thanks! Good having that clarified. For your convenience: The app with the new package name will [turn up here](https://apt.izzysoft.de/fdroid/index/apk/com.emmanuelkehinde.twittasave) in about 11h from now. The [entry for the former version](https://apt.izzysoft.de/fdroid/index/apk/com.kehinde.twittasave) will then have a notice pointing to the new one (if you want changes/additions to the description, just let me know).

Thanks to your providing the APK, people who rather avoid Play Store (like me: I do not even have GApps on my devices) can use my F-Droid repo to install/update your app. Due to the tracker status (your app comes with 3 "unwanted libraries"), some will still avoid it. As for myself: I've stopped using Twitter when they started blocking the client I've used. Moved to Mastodon years ago anyway, so I'm thankful to Twitter helping me saying my "final good-buy" :rofl:

**Comment by emmanuelkehinde** [comment]
Ohh 😊. Thank you.

**Comment by IzzySoft** [comment]
Oh, pleasepleaseplease: Do not forget to increase `versionCode` and adjust `versionName`. Your tag for `v3.0` has an APK claiming to be:

    package: name='com.emmanuelkehinde.twittasave' versionCode='1' versionName='1.0' compileSdkVersion='29' compileSdkVersionCodename='10'

This not only makes automated update checks impossible – but also will disable "update notifications" if I'd fetch them manually, as for Android the version would be still the same and no update. So may I suggest adjusting that to `versionCode='5' versionName='3.1'` and tag it `v3.1` – plus keep increasing `versionName` for all future releases as well as keeping `versionName` in sync with the tag name? Thanks!
