### ISSUE TITLE
Twitter mobile

### ISSUE THREAD

**Issue by Mattis142** [emmanuelkehinde/TwittaSave-Android#9]
Sharing the video using the "Share Tweet via …" button on the web version of Twitter doesn't start the download inside the app and instead just opens the app, I'd like to see this feature inside the app!

**Comment by emmanuelkehinde** [comment]
Hi @MKCOOL142 

Thanks for pointing that out. You can make use of the autolisten feature instead to achieve that, by simply tapping “Copy link to tweet” on Twitter.

**Comment by Mattis142** [comment]
Thank you for telling me this, I'll try it out!
